### ISSUE TITLE
Incorrect count of metrics for scheduledMetadata values returned from '/info' endpoint

### ISSUE THREAD

**Issue by alexcreasy** [trustyai-python/trustyai-explainability#323]
**Describe the bug**
When querying the '/info' endpoint, it returns an array of data for each model Trusty knows about. For each model there is a count of the number of scheduled metrics. The count for each metric is the total over all models, rather than the individual count for the model. Given the count json object is at the model level, this doesn't make sense as it is duplicated for each model.   

**Steps To Reproduce**
1. Add multiple models to TrustyAI (I used the `compose-generator-memory-multi-model.yaml` example)
2. Register at least one metric, for at least two models.
3. Query the '/info' endpoint.
4. Observe the `metrics.scheduledMetadata` object for each of the models.
5. You will see that the `spd` and `dir` counts are the total for all models on each model.

**Expected behavior**
The count should be the number of scheduled metrics per model.

**Workaround (if any)**
None.

**TrustyAI version**
main

**OpenShift Version**
N/A

**Additional context**

**Comment by ruivieira** [comment]
Thank you for spotting this, @alexcreasy. Please see #324.
