### ISSUE TITLE
Unable to configure bias-metrics 

### ISSUE THREAD

**Issue by nehachopra27** [trustyai-python/trustyai-explainability#395]
**Describe the bug**
Unable to create bias metrics for deployed models

**Steps To Reproduce**
1. Create a Model server
2. Deploy TrustyAI Service
3. Deploy the model
4. Send some inferences
5. Create a Bias Metrics

**Expected behavior**
Bias metrics to be created 

**TrustyAI version**
Please attach TrustyAI version or commit used.

**OpenShift Version**
(If applicable) Please attach OpenShift version used.
Version #: 4.13
Provider (Baremetal,
<img width="1151" alt="Screenshot 2023-10-17 at 15 04 35" src="https://github.com/trustyai-explainability/trustyai-explainability/assets/11557840/704ae192-e309-4d1c-9f84-e9c7867a8cc8">
 OpenStack, RHV, AWS, OKD, CodeReady Containers, ...):

**Additional context**

**Comment by RobGeada** [comment]
Fixed by https://github.com/trustyai-explainability/trustyai-explainability/pull/397
