### ISSUE TITLE
TrustyAI Maven CI timeouts

### ISSUE THREAD

**Issue by RobGeada** [trustyai-python/trustyai-explainability#474]
The following CI tests are consistently timing out on all PRs:

- Java 17 - Maven 3.9.2- Build and Test 
- Java 17 - Maven 3.6.3- Build and Test 

For some reason, these two tests take 4x as long as the other ones, and then time out. It's unclear which test is taking so long, and it's quite hard to replicate on a local `mvn test`. This is a relatively new issue, could it be related to some change in Optaplanner, and how that affects the counterfactual tests?

**Describe the bug**
A clear and concise description of what the bug is and how often it occurs

**Steps To Reproduce**

**Expected behavior**

**Workaround (if any)**
Any manual steps that allow you to resolve the issue

**TrustyAI version**
Please attach TrustyAI version or commit used.

**OpenShift Version**
(If applicable) Please attach OpenShift version used.
Version #: 
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...):

**Additional context**

**Comment by spolti** [comment]
The test in question is: 

```
Error:  [ERROR] testCounterfactualMatch{int}[3]  Time elapsed: 1,200.007 s  <<< ERROR!
java.util.concurrent.TimeoutException
	at org.kie.trustyai.explainability.local.counterfactual.CounterfactualExplainerTest.testCounterfactualMatch(CounterfactualExplainerTest.java:164)
```
